const Types = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  COMPARE_ADD: 'COMPARE_ADD',
  COMPARE_REMOVE: 'COMPARE_REMOVE',
  COMPARE_CLEAR: 'COMPARE_CLEAR',
}
export default Types;